<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "categories".
 *
 * @property integer $id
 * @property string $title
 * @property integer $parent_category_id
 * @property integer $label_class
 */
class Category extends \yii\db\ActiveRecord
{

    const LABEL_DEFAULT = 'label-default';
    const LABEL_INVERSE = 'label-inverse';
    const LABEL_PRIMARY = 'label-primary';
    const LABEL_SUCCESS = 'label-success';
    const LABEL_INFO = 'label-info';
    const LABEL_WARNING = 'label-warning';
    const LABEL_DANGER = 'label-danger';


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'categories';
    }

    /**
     * @return array
     */
    public function getLabelsArray()
    {
        return [
            self::LABEL_DEFAULT,
            self::LABEL_INVERSE,
            self::LABEL_PRIMARY,
            self::LABEL_SUCCESS,
            self::LABEL_INFO,
            self::LABEL_WARNING,
            self::LABEL_DANGER,
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title'], 'required'],
            [['parent_category_id'], 'integer'],
            [['label_class'], 'safe'],
            ['parent_category_id', 'default', 'value' => 0],
            [['title'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'parent_category_id' => 'Parent Category ID',
            'label_class' => 'Label Class',
        ];
    }

    /**
     * @return array
     */
    public static function getCategories()
    {
        $categories = Category::find()->all();
        return $categories;
    }


    /**
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        if ($insert) {
            $this->label_class = array_rand(Category::getLabelsArray());
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
